### ISSUE TITLE
Make the logos clickable

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/preparetocode#45]
It's a natural to want to click on a logo to go somwhere. Let's test that theory on this page : 

http://www.preparetocode.io/mac/useful/

**Comment by tjmabey** [comment]
i can do this! this will be my first pull request...

**Comment by leggsimon** [comment]
Please do @tjmabey

**Comment by criptodev** [comment]
Hello!, this issue is done?

**Comment by nikeshashar** [comment]
@criptodev Yes - sorry! https://github.com/makersacademy/preparetocode/pull/67
