### ISSUE TITLE
Page dot isn't highlighted on page load

### ISSUE THREAD

**Issue by suzannehamilton** [makersacademy/preparetocode#56]
Some of the set-up guides have multiple pages, so there's a line of dots to show you what page you're on, such as the Linux git guide: http://www.preparetocode.io/linux/essential/git.html

![screen shot 2016-12-03 at 15 28 03](https://cloud.githubusercontent.com/assets/754712/20860320/296ce548-b96d-11e6-8f21-5f77ce85ab02.png)

But when you first open a guide, the dot highlighting doesn't work for the first page:
![screen shot 2016-12-03 at 15 32 58](https://cloud.githubusercontent.com/assets/754712/20860351/ea867366-b96d-11e6-9075-6deed6d14343.png)

It does work if you go forwards and then go back to the first page - it's just broken on the initial page load.

**Comment by mdalmazan** [comment]
Is this still an issue? If it is, I would like to take it on. Best way to learn a language is by helping out the community, at least I think so.

**Comment by nikeshashar** [comment]
@mdalmazan yup go for it!
